### ISSUE TITLE
Cannot build: missing rollup config

### ISSUE THREAD

**Issue by Saltallica** [pixijs/pixi-sound#70]
Hi there, trying to build the bundled distribution for this project - 
I'm assuming ```npm run build``` is the proper command. 

I'm getting an error stating that the rollup.config.js is missing - I don't see it as part of the source code.  

Here's the full terminal dump if it helps:

```
> pixi-sound@2.0.2 prebuild /Users/sean/projects/PaperGorillas/src/js/ext/pixi-sound
> npm run clean && npm run lint


> pixi-sound@2.0.2 clean /Users/sean/projects/PaperGorillas/src/js/ext/pixi-sound
> rimraf dist/**


> pixi-sound@2.0.2 lint /Users/sean/projects/PaperGorillas/src/js/ext/pixi-sound
> tslint examples/**.js test/*.js src/**.ts rollup.config.js --format=stylish --fix



> pixi-sound@2.0.2 build /Users/sean/projects/PaperGorillas/src/js/ext/pixi-sound
> npm run build:umd && npm run build:es


> pixi-sound@2.0.2 build:umd /Users/sean/projects/PaperGorillas/src/js/ext/pixi-sound
> rollup -c -f umd -o dist/pixi-sound.js

Error: ENOENT: no such file or directory, lstat '/Users/sean/projects/PaperGorillas/src/js/ext/pixi-sound/rollup.config.js'
    at Object.realpathSync (fs.js:1657:15)
    at runRollup (/Users/sean/projects/PaperGorillas/src/js/ext/pixi-sound/node_modules/rollup/bin/rollup:653:16)
    at Object.<anonymous> (/Users/sean/projects/PaperGorillas/src/js/ext/pixi-sound/node_modules/rollup/bin/rollup:907:2)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
```

Thanks!

**Comment by bigtimebuddy** [comment]
@Saltallica, we do not publish the `src` or Rollup config in NPM. If you want to build it yourself, you have to clone from GitHub directly.

**Comment by Saltallica** [comment]
@bigtimebuddy Got it, sorry about the confusion. I was able to pull down the source and build with no issue - thanks again.
